language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install -r test_requirements.txt
env:
  - DUO_API_HOST=test
  - DUO_INT_KEY=test
  - DUO_SECRET_KEY=test
script:
  - pytest -n auto